valor = int(input('Digite um valor inteiro: '))
print('A tabuada de {}, será:'.format(valor))
print('-'*12)
print(valor, 'x 0  = {}'.format(valor * 0))
print(valor, 'x 1  = {}'.format(valor * 1))
print(valor, 'x 2  = {}'.format(valor * 2))
print(valor, 'x 3  = {}'.format(valor * 3))
print(valor, 'x 4  = {}'.format(valor * 4))
print(valor, 'x 5  = {}'.format(valor * 5))
print(valor, 'x 6  = {}'.format(valor * 6))
print(valor, 'x 7  = {}'.format(valor * 7))
print(valor, 'x 8  = {}'.format(valor * 8))
print(valor, 'x 9  = {}'.format(valor * 9))
print(valor, 'x 10 = {}'.format(valor * 10))
print('-'*12)
